### PR TITLE
CB: #WEB-248

### PR DESCRIPTION
**Pull request by carlosbazana**
This blog post has the following features:

- [ ] A GitHub Repository with a polished README
- [ ] A GitHub Repository under the github.com/oktadeveloper account
- [ ] A title that's approved by Dev Advocacy
- [ ] A URL that's approved by Dev Advocacy
- [ ] The content has been ran through Grammarly (https://www.grammarly.com/)
- [ ] Rendered locally and confirmed that no Markdown typos exist

### CODE REVIEW

**Comment by hamzaessaoui-okta** [comment]
@carlosbazana This is looking really good. 
Can you adjust the font-size/weight, placeholder/link color and logo size?

Please use https://5fe125cf45ed061f8a940c65--reverent-murdock-829d24.netlify.app/pricing/ as a reference

**Comment by hamzaessaoui-okta** [comment]
@carlosbazana Looks great!
Some feedback:
- [ ] In the footer: "Forum" in "Need support? Contact developers@okta.com or ask on the forum." is missing an href
- [ ] Footer items look more spaced out than the comp or https://5fe4c8c6823575b2076a3e1c--reverent-murdock-829d24.netlify.app/
- [ ] Footer section is using some title case vs sentence case
- [ ] Missing the RSS icon in footer
- [ ] Youtube icon in footer also looks incorrect
- [ ] all links with target="_blank" (especially pointing out) should have rel="noopener noreferrer" attributes:question_mark:
- [ ] https://owasp.org/www-community/attacks/Reverse_Tabnabbing
- [ ] In the footer, the external link icons look mis-aligned
- [ ] okta.com headings as well as Social, Contact & Legal, etc look like the wrong font
- [ ] See the other header for reference: https://5fe4c8c6823575b2076a3e1c--reverent-murdock-829d24.netlify.app/

**Comment by hamzaessaoui-okta** [comment]
@carlosbazana could you please mail developer@okta.com email a link (mailto)

**Comment by carlosbazana** [comment]
Added the mailto link, @hamzaessaoui-okta

**Review by rdegges — APPROVED** [review]

**Pull request merged**
