### PR TITLE
Update Laravel Vue post to use CLI for setup

### PR DESCRIPTION
**Pull request by mraible**
Updates [Build a Basic CRUD App with Laravel and Vue](https://developer.okta.com/blog/2019/01/15/crud-app-laravel-vue) to streamline setup. 

Example app updates in https://github.com/oktadeveloper/okta-php-laravel-vue-crud-example/pull/20.

### CODE REVIEW

**Comment by aaronpk** [comment]
So these changes are fine, but this blog post isn't really functional right now because it doesn't pin the Laravel version and it relies on an old version of Laravel to get through the instructions. If the scope of this change is to just update the setup instructions it can be merged as is, but if we need to actually update the post so that it works today it'll be a lot more work.

**Comment by mraible** [comment]
Is it possible to just pin the version as part of the install? If so, that might be the best solution. Then, create a new assignment to create a similar one that uses the latest versions.

**Comment by aaronpk** [comment]
I had to look it up, but yes thankfully that is possible!

**Comment by mraible** [comment]
@aaronpk I updated the code and this post to use Okta Vue 3.1.0. I did this because I believe the previous version used did not support PKCE, which means the app that CLI creates wouldn't work. I did NOT QA, I just updated the code.

**Comment by aaronpk** [comment]
I had to pin a few more libraries to old versions, but everything installs now. Unfortunately it looks like some of the libraries are too old to work in PHP 7.4 so ultimately I wasn't able to get this to work. But at least it's less broken now than it was before.

**Review by aaronpk — APPROVED** [review]

**Pull request merged**
