### PR TITLE
Add blog post on JHipster + Quarkus

### PR DESCRIPTION
**Pull request by danielpetisme**
This blog post has the following features:

- [ ] A GitHub Repository with a polished README
- [x] A GitHub Repository under the github.com/oktadeveloper account
- [x] A title that's approved by Dev Advocacy
- [x] A URL that's approved by Dev Advocacy
- [x] The content has been run through Grammarly (https://www.grammarly.com/)
- [x] Rendered locally and confirmed that no Markdown typos exist
- [x] Update post with Okta CLI version

As discussed with @mraible I will propose the blog post about how to build a secured Quarkus application via JHipster, the Quarkus blueprint, and Okta.

### CODE REVIEW

**Comment by danielpetisme** [comment]
@mraible I think the article is ready for a first review.

Can you help me please. Don't hesitate to include okta folks into the discussion if it make sense.

Thank you hipster

**Comment by mraible** [comment]
Great! @bdemers is adding Quarkus support to our CLI. When he releases that, I'll QA this post and update it to use the latest CLI version.

**Comment by danielpetisme** [comment]
🤔

The CLI will cover the pure Quarkus config only
Be sure that I plan to complete with the JHipster Quarkus config too but it
will come after.
Both configs are not exactly the same.

For me, either the article is independent of the CLI merge or we wait for a
full Jhipster Quarkus support (ie. Quarkus then Jhipster Quarkus)

WDYT?

Le ven. 29 janv. 2021 à 22:25, Matt Raible <notifications@github.com> a
écrit :

**Comment by mraible** [comment]
I believe the next release of the CLI will have Quarkus standalone support, as well as JHipster Quarkus support.

**Comment by danielpetisme** [comment]
The ongoing PR I made cover Quarkus only.
As soon as it's merged, be sure I'll open the one about Jhipster Quarkus
just after 😎 I have the prototype on my laptop 🤭

Le ven. 29 janv. 2021 à 22:37, Matt Raible <notifications@github.com> a
écrit :

**Comment by mraible** [comment]
@bdemers Do you have an update on Quarkus support for JHipster in the Okta CLI? I'm on vacation for the last two weeks in February, so it'd be nice if we could get a release next week and get this post ready to publish too.

**Comment by bdemers** [comment]
I rebased the Quarkus bits, everything looked good, just needs a quick round of testing and it should be good. Last week was a bit hectic, but I’ll try to wrap this up Monday.

**Comment by mraible** [comment]
@danielpetisme I started tech reviewing this post and pushed my changes in [`b852fe3` (#503)](https://github.com/oktadeveloper/okta-blog/pull/503/commits/b852fe33d5e4981317db6f6a4cdaba8fcaf99077). I'll continue tomorrow (Thursday, Feb 11). 

Note that the Okta CLI removes the sections where you need to create groups, add users to groups, and create a `groups` claim. I still think it's a good idea to show how to do these steps, but we should show the quick way (`okta apps create jhipster` with the CLI) first. 

I also think we should create the app first before we even get into Okta because readers will want to see a Quarkus app running as soon as possible.

Finally, I did some keyword research for this post and `quarkus java` (at 1600 searches per month) seems to be the most popular. We should try to use those terms in the title and first few headings.

**Comment by mraible** [comment]
@danielpetisme I didn't get a chance to work on this today. The Okta CLI changes needed to streamline things seems to be [very close](https://github.com/okta/okta-cli/pull/82). I'll look again tomorrow (Friday, Feb 12).

**Comment by mraible** [comment]
@danielpetisme I just sent you and @bdemers a link to the Google Doc I created from this PR. We like to use Google Docs for our reviews. You should consider it the "source of truth" going forward. I can handle copying everything back into this document after we're finished with tech and copy editing.

**Comment by mraible** [comment]
This post is dependent on https://github.com/okta/okta-cli/pull/82. Related: we need to add the Okta CLI version number to use before publishing.

**Review by mraible — APPROVED** [review]

**Pull request merged**
