### PR TITLE
upgrade to jekyll-asciidoc 3 and Asciidoctor 2 remove asciidoctor-rouge

### PR DESCRIPTION
**Pull request by mojavelinux**
If you install jekyll-asciidoc without a version, you will get the 3.0.0 release. The 3.0.0 release allows the version of Asciidoctor to float (up to 2.0.10). Since Asciidoctor 2, asciidoctor-rouge is obsolete. So basically, just delete it and you'll be working again.

### CODE REVIEW

**Comment by mraible** [comment]
@mojavelinux It looks like the bundler update to 2.0.2 is causing the build to fail.

```
12:54:23 PM: Could not find 'bundler' (2.0.2) required by your /opt/build/repo/Gemfile.lock.
12:54:23 PM: To update to the latest version installed on your system, run `bundle update --bundler`.
12:54:23 PM: To install the missing version, run `gem install bundler:2.0.2`
12:54:23 PM: Checked in 'GEM_PATH=/opt/buildhome/.rvm/gems/ruby-2.6.2:/opt/buildhome/.rvm/rubies/ruby-2.6.2/lib/ruby/gems/2.6.0', execute `gem env` for more information
12:54:23 PM: To install the version of bundler this project requires, run `gem install bundler -v '2.0.2'
```

Is the upgrade required to fix things?

**Comment by mojavelinux** [comment]
This is unrelated and has to do with the very rough transition from Bundler
1 to 2. The solution is to make sure you have the latest bundler installed,
then delete Gemfile.lock and run bundle again. At some point, you'll have
to make this transition, so might as well take care of it.

**Comment by rdegges** [comment]
Thanks @mojavelinux =) You are awesome. I just upgraded our bundler stuff in the build system. <333

**Comment by rdegges** [comment]
We are total ruby noobs over here =)

**Comment by mojavelinux** [comment]
Nice work!

**Pull request merged**
