### PR TITLE
Adding a Makefile

### PR DESCRIPTION
**Pull request by rdegges**
This will use Docker to make working with the blog much simpler.

### CODE REVIEW

**Comment by mraible** [comment]
It seems like we're complicating things. I don't use Docker and the `npm` commands just work fine for me. Now we're adding a `Makefile` just to support the Docker commands. Yuck.

**Comment by rdegges** [comment]
Ya, I'm not 100% sure if this is the right direction. The way I was thinking about it was that: ideally, you'd just use Docker. So maybe using Make (since it's included on every OS) would make it easy so you don't have to remember long Docker commands? IDK.

**Comment by mraible** [comment]
I don't use Docker. You might be the only one. @leebrandt, @aaronpk, @Quorralyne, @reverentgeek, @dogeared, @bdemers: do y'all use Docker or npm?

**Comment by aaronpk** [comment]
I don't use Docker, and I don't want to have to use it either lol! I don't care if other people do but I just want to run `npm` directly.

**Comment by rdegges** [comment]
Really? I'm a little surprised, heh. It makes it much simpler since the only thing you need installed on your laptop is Docker (nothing special required). It'll handle the install of Ruby/NPM/all the dependencies and everything :o

**Comment by leebrandt** [comment]
I do use Docker quite extensively.

**Pull request merged**
