### PR TITLE
Style rules added to Changelog anchor on BlogPost

### PR DESCRIPTION
**Pull request by emmanuelgonzalez-okta**

### CODE REVIEW

**Comment by mraible** [comment]
Looks good! Tested on https://deploy-preview-691--okta-blog.netlify.app/blog/2021/01/20/reactive-java-microservices#changelog.

**Review by mraible — APPROVED** [review]

**Comment by mraible** [comment]
I think we should make a similar change for our H2 and H3 headers (or maybe all headers for that matter). When we go to them from a table of contents, the header is hidden.

For example:

https://deploy-preview-691--okta-blog.netlify.app/blog/2021/01/20/reactive-java-microservices#run-your-reactive-java-microservices

**Comment by hamzaessaoui-okta** [comment]
@mraible if you could create a ticket, we can run it by design and submit a PR

**Comment by mraible** [comment]
@hamzaessaoui-okta I created https://github.com/oktadeveloper/okta-blog/pull/693, which seems to solve the problem.

**Pull request merged**
