### PR TITLE
Issue/30 - PostgreSQL with Spring Boot

### PR DESCRIPTION
**Pull request by raphaeldovale**
Please make sure the below checklist is followed for Pull Requests.

- [x] Tests are passing 
- [ ] Front matter has a social image
- [x] Images are optimized and sized appropriately
- [ ] If post has a GitHub repo, it has a README with instructions, a link back to the blog post, and a title/URL at the top
- [x] Post has been viewed locally in a browser

### CODE REVIEW

**Comment by raphaeldovale** [comment]
Didn't add my profile again because it already has with my latest article. Master was not updated with it yet.

**Comment by raphaeldovale** [comment]
@mraible are those CI working? Should I be worried? =)

**Comment by mraible** [comment]
@raphaeldovale Don't worry about the CI tests. They're [currently broken](https://github.com/oktadeveloper/okta-blog/issues/13).

**Comment by mraible** [comment]
Closing in favor of https://github.com/okta/okta.github.io/pull/2718.

@raphaeldovale I refactored the `artifactId` and package name to be simply `postgresql`. I also updated the Spring Initializr screenshot. Will copy/paste into a Google doc for Lindsay to review now.

**Pull request closed without merging**
